### ISSUE TITLE
Raising NSException

### ISSUE THREAD

**Issue by colasjojo** [AliSoftware/OHPDFImage#6]
Hi Ali,

what do you think of adding an exception in `OHVectorImage.m`: if the size has a zero-coordinate, we stop the process?

```
- (UIImage*)renderAtSize:(CGSize)size
{
    // Handle bad cases
    if (size.width <= 0
        ||
        size.height <= 0)
    {
        [NSException raise:NSInvalidArgumentException
                    format:@"The size given must have positive coordinates"] ;
    }

(... the normal method)
}
```

As one of my IBOutlet was not set, a zero size was given to the parameters. With this exception, I am able to detect very easily where the problem is.

**Comment by AliSoftware** [comment]
I'm not fond of exceptions, and, with the rise of Swift — which cannot catch exceptions — I tend to move away from them even more.

Besides, one generally does not want its code to crash even when the size is zero width or height because it might be a case that actually happen (think about e.g. having to toggle a view's height to show/hide it for example, this view might have a zero-height when hidden and if it contains an `UIImageView` in which you render your `OHPDFImage` in it, you don't wan't your code to crash when you hide the view by changing its height to zero)

If you really want a reminder or helpful message when you use a zero-width or zero-height size, I'd probably rather have an `NSLog` to help the developer debug than an `NSException`.

**Comment by colasjojo** [comment]
Thanks for the answer and the explanations. I guess you are right.But, when the size is zero I get many errors in the console.Envoyé depuis Yahoo Mail pour iPadÀ 11 févr. 2015 23:42:43, AliSoftware a écrit :I'm not fond of exceptions, and, with the rise of Swift — which cannot catch exceptions — I tend to move away from them even more.

Besides, one generally does not want its code to crash even when the size is zero width or height because it might be a case that actually happen (think about e.g. having to toggle a view's height to show/hide it for example, this view might have a zero-height when hidden and if it contains an UIImageView in which you render your OHPDFImage in it, you don't wan't your code to crash when you hide the view by changing its height to zero)

If you really want a reminder or helpful message when you use a zero-width or zero-height size, I'd probably rather have an NSLog to help the developer debug than an NSException.

**Comment by colasjojo** [comment]
Here is a copy of the error stack when passing a zero `CGSize`, in case you are interested.

```
Feb 13 15:31:10 MyApp[2611] <Error>: CGContextSaveGState: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Feb 13 15:31:10 MyApp[2611] <Error>: CGContextConcatCTM: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Feb 13 15:31:10 MyApp[2611] <Error>: CGContextConcatCTM: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Feb 13 15:31:10 MyApp[2611] <Error>: CGContextConcatCTM: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Feb 13 15:31:10 MyApp[2611] <Error>: CGContextConcatCTM: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Feb 13 15:31:10 MyApp[2611] <Error>: CGContextRestoreGState: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Feb 13 15:31:10 MyApp[2611] <Error>: CGContextClipToMask: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Feb 13 15:31:10 MyApp[2611] <Error>: CGContextSetFillColorWithColor: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Feb 13 15:31:10 MyApp[2611] <Error>: CGContextFillRects: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Feb 13 15:31:10 MyApp[2611] <Error>: CGContextDrawImage: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
```

**Comment by AliSoftware** [comment]
Then we should add security checks in the `OHPDFImage` code to return a `nil` or empty image in that case without even trying to render the zero-sized bitmap.

Don't hesitate to submit a PR for that, I'm really busy lately and sadly won't have time to spend much time on my code (I hope this will change soon, but priorities are not always what we want them to be ;-))

**Comment by colasjojo** [comment]
OK I'll do that with pleasure. Your library is really great !
